### ISSUE TITLE
Add macos 12 support

### ISSUE THREAD

**Issue by farstarx** [RSKGroup/smc_exporter#1]
Hello, Eric!

This is my first issue and I didn't manage to contact you in another way.
I have 2 requests:
1) Could you please add support for old systems based on MacOS 12.
I have some devices that I can't update but need to monitor temperatures.
Now smc_exporter doesn't run on it:

```
# /usr/local/bin/smc_exporter 
dyld[85031]: Symbol not found: _$s10Foundation12CharacterSetV11whitespacesACvgZ
  Referenced from: /usr/local/bin/smc_exporter
  Expected in: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
Abort trap: 6
```

2) I notices that temperature values are inside metric labels:
```
rsk_sensor{computername="mac01",sensorid="TC0F",name="CPU diode filtered",type="Temperature",value="32.62"} 32.62
rsk_sensor{computername="mac01",sensorid="TC0P",name="CPU proximity",type="Temperature",value="28.44"} 28.44
rsk_sensor{computername="mac01",sensorid="TCGC",name="GPU Intel Graphics",type="Temperature",value="32.00"} 32.00
rsk_sensor{computername="mac01",sensorid="TW0P",name="Airport",type="Temperature",value="28.19"} 28.19
```
This leads to a low cardinality while saving timeseries in prometheus database.
I need to drop label "value" to get proper results in prometheus:

```
    metric_relabel_configs:
      - action: labeldrop
        regex: "value" # drop value label in rsk_sensor (smc_exporter)
```

To get something like this:

```
{__name__="rsk_sensor", computername="mac01", env="production", instance="mac01", job="node-macos", name="CPU diode filtered", region="UK", sensorid="TC0F", type="Temperature"} 34.1
```

Thank you!

**Comment by ehemmete** [comment]
I bumped the minimum version back to macOS 12.4.  I also took the opportunity to update smc.swift from its source. 
For #2, I'm glad you have a solution.  I don't want to make a change to the format at this point.  
Please test the new release and see if it does what you need.

**Comment by farstarx** [comment]
Yes, it works now. Tested on 12.4 and 12.3.

Thank you!
